import React, { Component } from "react";
import { connect } from "react-redux";
import * as actions from "../../actions";
import API from "../../utils/API";
import { Link } from "react-router-dom";
import Header from "../../components/Navs/Header";
// import { Row, Col } from "../../components/Grid";
import SideBar from "../../components/Sidebar/Sidebar";
import "./AdminForm.css";

class Admin extends Component {
  state = {
    user: {},
    stripe: "",

  };

  loadCurrentUser = () => {
    fetch("/api/current_user")
      .then(res => res.json())
      .then(
        result => {
          console.log("result", result);
          this.setState({
            isLoaded: true,
            user: result
          });
        },
        // Note: it's important to handle errors here
        // instead of a catch() block so that we don't swallow
        // exceptions from actual bugs in components.
        error => {
          this.setState({
            isLoaded: true,
            error
          });
        }
      );
  };

  componentDidMount() {
    console.log("COMPONENT MOUNTED");
    this.props.fetchUser();
    this.loadCurrentUser();
    console.log("user", this.state.user);
  }

  changeUserStatus = () => {
    console.log("STATEEEEEEEEE", this.state.user);
    const currentUser = this.state.user._id;
    // const boolean = true
    API.changeUser(currentUser)
      .then(console.log("success"))
      .catch(err => console.log(err));
    window.location.reload();
  };

  //  Function to handle form input
  handleInputChange = event => {
    let { value } = event.target;
    console.log(value);
    this.setState({ stripe: value });
  };

  // Function to handle form submit
  handleFormSubmit = event => {
    const currentUser = this.state.user._id;
    const stripeAccount = { stripeAccount: this.state.stripe };
    console.log("stripeAccount", stripeAccount);
    console.log("currentUser", currentUser);

    API.changetoAdmin(currentUser, stripeAccount)
      .then(console.log("success"))
      .catch(err => console.log(err));
  };

  render() {
    return (
      <div className="adminGrid">
        <Header />
        <SideBar user={this.state.user} />
        <div className="adminMessage">
          <h2 className="adminHeader">
            Before you can get started, please sign up with stripe
          </h2>
          <button className="submit btn">
            <a href="https://connect.stripe.com/oauth/authorize?response_type=code&client_id=ca_DW5XNKTvUAeODU0hK38cYryqiz6QGJFF&scope=read_write">
              Connect with Stripe
            </a>
          </button>
          <form className="formStyle">
            <div className="form-group">
              <label className="adminHeader2" htmlFor="stripe">
                Stripe Account ID:{" "}
              </label>
              <input
                value={this.state.stripe}
                onChange={this.handleInputChange}
                type="integer"
                className="form-control titleInput"
                id="title"
                name="title"
                placeholder="Please enter your stripe account ID generated by signing up with stripe above"
              />
            </div>
          </form>
          <Link to="/">
            <button
              className="submit btn"
              onClick={() => this.handleFormSubmit()}
            >
              Become an Admin
            </button>
          </Link>
        </div>
      </div>
    );
  }
}

export default connect(
  null,
  actions
)(Admin);
